### PR TITLE
Additional functionality for managing CAS users

### PR DESCRIPTION
**Pull request by PeterTHM**
Hi,
I'm a student at the Technische-Hochschule-Mittelhessen in germany and part of the iCampus development group. Since we migrated the website of our department 'MNI' to Joomla 3.x, we changed from using a self-developed CAS solution to your project. In order to fit the needs of our department site, we made a few additions to the project:
- In the user manager of the external login component, we added a button 'Enable/Disable Global' to the toolbar. This leads to the server overview just like the 'Enable External Login' button, but will show options to activate and deactivate a server for all users with one click. We added this, because we had about 5000+ existing users when we first installed 'External login' and had to activate them all to login via CAS.

global
- The second change was made to the access mangement. We discovered that users that are not activated for a paricular CAS-Server in the backend, could still login when the verification from the CAS-Server was successfull. We added some access control additions to manage this issue.
- The third change is a addition to the site modul and the cas system plugin.
  Although there is already a option in the backend to switch between logout locally or global from a CAS-Server, our users would like to have both options in the frontend. So we added a option for that in the advanced options of the site module.

module logout

module logout page

We think this additions could also be usefull for other users of this project and it would be cool if they make it in the joomla-external-login project.

Greetings
Peter

### CODE REVIEW

**Comment by chdemko** [comment]
Thank for this big contribution!

**Comment by chdemko** [comment]
Hello @PeterJTHM , I had not the time to merge your work. Could you please update your branch to ly current master branch?

**Comment by PeterTHM** [comment]
Hello! Please excuse me for the delayed reply. I'm currently working on it :)

**Comment by PeterTHM** [comment]
Hi! I've merged the project.

**Pull request merged**
